// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtupIb8fQ6Bt-npxuQZZeS8zDBc2SmMXM',
    appId: '1:658226305344:web:a4f9dbd1fcffdc3e2d82a5',
    messagingSenderId: '658226305344',
    projectId: 'fooddeliverydw',
    authDomain: 'fooddeliverydw.firebaseapp.com',
    databaseURL: 'https://fooddeliverydw-default-rtdb.firebaseio.com',
    storageBucket: 'fooddeliverydw.appspot.com',
    measurementId: 'G-Y4HTMWRWJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRoBS1ez7GcH9lG8C8MplL4N-yfsAk5Oc',
    appId: '1:658226305344:android:e2bec52d80d4d6812d82a5',
    messagingSenderId: '658226305344',
    projectId: 'fooddeliverydw',
    databaseURL: 'https://fooddeliverydw-default-rtdb.firebaseio.com',
    storageBucket: 'fooddeliverydw.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGzGrSKOgGWHJBPW5vHcEzIzC4ZJTBi_4',
    appId: '1:658226305344:ios:4751d4b52f415d1e2d82a5',
    messagingSenderId: '658226305344',
    projectId: 'fooddeliverydw',
    databaseURL: 'https://fooddeliverydw-default-rtdb.firebaseio.com',
    storageBucket: 'fooddeliverydw.appspot.com',
    androidClientId: '658226305344-15n9s8jghmqk197cpb3kqk4u9cs8qs90.apps.googleusercontent.com',
    iosClientId: '658226305344-jrnk2d3ondc08u71id5hdqo04dsa37m3.apps.googleusercontent.com',
    iosBundleId: 'com.dw373103.FoodRestaurantApp',
  );

}